function raw = importOralSA(filename, dataLines)
%IMPORTFILE Import data from a text file
%  H08M = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  H08M = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  h08m = importfile("\\128.95.12.244\kcoffey\Coffey Lab\2021.06.10 K99 Data\2022.02.28 LHb Oral Fentanyl\2022.03.07 Oral SA Round 1\Oral SA Behavior\!2022-03-11_12h08m.Subject R1", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-May-2022 15:32:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["  ", "   ", "    ", "     ", "      ", "       ", "        ", ";"];

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName2", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName2", "ThousandsSeparator", ",");

% Import the data
raw = readtable(filename, opts);


end